default: &DEFAULT
run: 1
dim: 'FNO2D'
exit_signal_handler: True
exit_duration_in_mins: None
resume_from_checkpoint: None
save_path: '/p/project1/cexalab/john2/NeuralOperators/neural_operators/results/strategy4'
verbose: True

data:
  subdomain_process: True
  subdomain_args: 
    start_time: 55.0
    stop_time: 57.2
    ndomain_x: 4
    ndomain_y: 1
    train_root_path: '/p/scratch/cexalab/john2/RBC2D_data_dt1e_1/RBC2D_NX256_NZ64_TI0_TF150_Pr1_Ra1e7_dt0_1_train'
    val_root_path: '/p/scratch/cexalab/john2/RBC2D_data_dt1e_1/RBC2D_NX256_NZ64_TI0_TF150_Pr1_Ra1e7_dt0_1_val'
    subdomain_data_path: '/p/project1/cexalab/john2/NeuralOperators/RayleighBernardConvection/processed_data/dt1e_1/RBC2D_NX4_256_NZ1_64_TI55_TF157_2_Pr1_Ra1e7_dt0_1.h5'
  train_data_path: '/p/project1/cexalab/john2/NeuralOperators/RayleighBernardConvection/processed_data/dt1e_1/RBC2D_NX256_NZ64_TI0_TF150_Pr1_Ra1e7_dt0_1.h5'
  val_data_path: '/p/project1/cexalab/john2/NeuralOperators/RayleighBernardConvection/processed_data/dt1e_1/RBC2D_NX256_NZ64_TI0_TF150_Pr1_Ra1e7_dt0_1.h5'
  train_samples: 50                 
  val_samples: 25                   
  multistep : True
  processed_data_path: '/p/project1/cexalab/john2/NeuralOperators/RayleighBernardConvection/processed_data/dt1e_1/RBC2D_NX4_256_NZ1_64_TI55_TF157_2_Pr1_Ra1e7_dt0_1_multi.h5'
  dt: 0.1
  gridx: 256
  gridy: 64
  xStep: 1
  yStep: 1
  tStep: 1
  start_index: 550
  stop_index: 572
  timestep: 1
  batch_size: 32
  rayleigh_number: 1e7
  prandtl_number: 1
  
FNO:
  modes: 12
  lifting_width: 128
  width: 256
  projection_width: 128
  n_layers: 4
  T_in: 1
  T: 1
  non_linearity: 'ReLU'
  
opt:
  epochs: 50
  learning_rate: 0.00039
  weight_decay: 1e-5
  scheduler_step: 100.0
  scheduler_gamma: 0.98
  T_max: 3 # For cosine only, typically take epochs
  
inference:
  do_inference: True
  model_checkpoint: '/p/project1/cexalab/john2/NeuralOperators/neural_operators/results/strategy2/rbc_fno2d_time_N10_epoch6_m12_w20_bs1_dt0.01_tin1_run1/checkpoint/model_checkpoint_5.pt'
  output_timesteps: 1
  output_error: True
  save_inference: True
  plot_cross_section: True
  test_data_path: '/p/project1/cexalab/john2/NeuralOperators/RayleighBernardConvection/processed_data/RBC2D_NX256_NZ64_TI80_TF83_Pr1_Ra1_5e7_dt0_001_test.h5'
  test_start_index: 0
  test_stop_index: 1
  test_timestep: 1
  test_dedalus_index: 80000
  test_batch_size: 2
