default: &DEFAULT
run: 1
dim: 'FNO3D'
exit_signal_handler: True
exit_duration_in_mins: None
resume_from_checkpoint: None
save_path: '/p/project1/cexalab/john2/NeuralOperators/neural_operators/results/strategy3'
verbose: True

data:
  data_path: '/p/project1/cexalab/john2/NeuralOperators/RayleighBernardConvection/processed_data/RBC2D_NX256_NZ64_TI0_TF150_Pr1_Ra1e7_dt0_1.h5'
  train_data_path: None
  val_data_path: None
  test_data_path: None
  train_samples: 10
  val_samples: 5
  test_samples: 5
  dt: 0.1
  gridx: 256
  gridy: 64
  xStep: 1
  yStep: 1
  tStep: 1
  start_index: 0
  stop_index: 2
  timestep: 1
  batch_size: 1

FNO:
  modes: 12
  width: 20
  T_in: 1
  T: 1
  
opt:
  epochs: 3
  learning_rate: 0.00039
  weight_decay: 1e-5
  scheduler_step: 100.0
  scheduler_gamma: 0.98
  T_max: 3 # For cosine only, typically take epochs
  

