simu:
  dataDir: simuData
  tInit: 100
  nSimu: 10
  dtData: 0.1
  tEnd: 100

sample:
  inSize: 1
  outStep: 10
  inStep: 5

data:
  outType: solution
  outScaling: 1
  dataFile: dataset_dt1e-3.h5
  trainRatio: 0.8
  seed: null
  batchSize: 20
  xStep: 1
  yStep: 1

model:
  da: 4
  du: 4
  dv: 16
  kX: 12
  kY: 12
  nLayers: 2
  forceFFT: false
  bias: true

optim:
  name: adam
  lr: 0.0001
  weight_decay: 1.0e-5
  absLoss: false

lr_scheduler:
  scheduler: StepLR
  step_size: 100.0
  gamma: 0.98

parallel_strategy:
  ddp: True      # Distributed Data Parallel
  gpus_per_node: 4

train:
  trainDir: training_dt1e-3_bias
  nEpochs: 1500
  checkpoint: model.pt
  lossesFile: losses.txt
  saveEvery: 100
  savePermanent: false
  noTensorboard: false
  logPrint: false

eval:
  iSimu: 8
  imgExt: png
  evalDir: evalDir